import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import React from 'react'
import Footer from './Footer'
import Header from './Header'
import * as siteConfig from '../../config/site.config'
import LoadingBar from 'react-top-loading-bar'

export default function Layout({ children }: { children: JSX.Element }) {
  const color = "##FFFFFF";
  const title = `${siteConfig.title}`
  const url = `${siteConfig.app_url}`
  const des = `Reviews from satisfied clients/customers can now be collected easily with ReviewGush using video, images, text, ratings, or even a combination of all four formats.`
  const keywords = `reviews, collect reviews, share reviews, manage reviews, embed reviews, coaches reviews, review, client reviews, customers reviews, video reviews, wall of love, sales reviews, course creation, business tools, smes`
  const og_image = `${url}/icons/512.png`;
  const { primary, secondary } = siteConfig.color;


  return (
    <Box>
      <Head>
        <title>Reviewgush</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Head>
        <title>{title}</title>

        {/* meta */}
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="robots" content="index, follow" />
        <meta name="description" content={des} />
        <meta name="keywords" content={keywords} />
        <meta name="author" content="Joseph O. Ajibodu" />

        {/* Favicon */}
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color={`${secondary}`} />
        <meta name="msapplication-TileColor" content={`${primary}`} />


        {/* Facebook Meta Tags */}
        <meta property="og:url" content={url} />
        <meta property="og:type" content="website" />
        <meta property="og:title" content={title} />
        <meta property="og:description" content={des} />
        <meta property="og:image" content={og_image} />

        {/* Twitter Meta Tags */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta property="twitter:domain" content={url} />
        <meta property="twitter:url" content={url} />
        <meta name="twitter:title" content={title} />
        <meta name="twitter:description" content={des} />
        <meta name="twitter:image" content={og_image} />

        {/* Open Graph data */}
        <meta property="og:title" content={title} />
        <meta property="og:type" content="website" />
        <meta property="og:url" content={url} />
        <meta property="og:image" content={og_image} />
        <meta property="og:description" content={des} />
        <meta property="og:site_name" content={siteConfig.title} />

        {/* Browser Color */}
        <meta name="theme-color" content={color} />
        <meta name="msapplication-navbutton-color" content={color} />
        {/* Do not add <script> tags using next/head 
        See more info here: https://nextjs.org/docs/messages/no-script-tags-in-head-component  */}
      </Head>

      <Box>
        <Header />
        {children}
        <Footer />
      </Box>
    </Box>
  )
}
